language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
install:
# command to install dependencies
  - "pip install coveralls"
  - pip install -q Django==$DJANGO --use-mirrors
  - "pip install ."
# command to run tests
script:
  - coverage run --branch --source=data_interrogator manage.py test
after_success:
  - coveralls
