language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO=3.0
install:
# command to install dependencies
  - "pip install coveralls"
  - pip install -q Django==$DJANGO
  - "pip install ."
# command to run tests
script:
  - PYTHONPATH=./app coverage run --branch --source=data_interrogator manage.py test
after_success:
  - coveralls
