# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 12:33
from __future__ import unicode_literals

from django.db import migrations
from ..data import create_initial_data, delete_initial_data


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, delete_initial_data)
    ]
