# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('base_model', models.CharField(max_length=100)),
                ('limit', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataTablePageColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, help_text=b'The text displayed in the table header for this column', max_length=255, null=True)),
                ('column_definition', models.TextField(help_text=b'The definition used to extract data from the database')),
                ('position', models.PositiveSmallIntegerField(verbose_name=b'Position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DataTablePageFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_definition', models.TextField(help_text=b'The definition used to extract data from the database')),
            ],
        ),
        migrations.CreateModel(
            name='DataTablePageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataTablePage',
            fields=[
                ('datatable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data_interrogator.DataTable')),
                ('url', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'published', b'Published')], default=b'draft', help_text='Draft items will only be seen by super users, published items can be seen by those allowed by the registration required field.', max_length=20)),
                ('registration_required', models.BooleanField(default=False, help_text='If this is checked, only logged-in users will be able to view the page.', verbose_name='registration required')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'exampleapp/contact_page.html'. If this isn't provided, the system will use 'data_interrogator/by_the_book.html'.", max_length=70, verbose_name='template name')),
            ],
            options={
                'ordering': ('url',),
            },
            bases=('data_interrogator.datatable',),
        ),
        migrations.AddField(
            model_name='datatablepageorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='data_interrogator.DataTable'),
        ),
        migrations.AddField(
            model_name='datatablepagefilter',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='data_interrogator.DataTable'),
        ),
        migrations.AddField(
            model_name='datatablepagecolumn',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='data_interrogator.DataTable'),
        ),
    ]
