# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_interrogator', '0002_auto_20160219_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='base_model',
            field=models.CharField(choices=[(b'parlhand:Person', b'Person'), (b'parlhand:Electorate', b'Electorate'), (b'parlhand:Shadow Ministry', b'Shadow Ministry'), (b'parlhand:Ministry', b'Ministry'), (b'parlhand:Party', b'Party'), (b'parlhand:Committee', b'Committee'), (b'parlhand:Service', b'Service'), (b'parlhand:Election', b'Election'), (b'ausfedparlhand:Occupation', b'Occupation'), (b'ausfedparlhand:Qualification', b'Qualification'), (b'ausfedparlhand:CurrentMember', b'CurrentMember'), (b'ausfedparlhand:CurrentSenator', b'CurrentSenator')], max_length=100),
        ),
    ]
