# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[(b'VIC', b'VIC'), (b'NSW', b'NSW'), (b'QLD', b'QLD'), (b'TAS', b'TAS'), (b'SA', b'SA'), (b'WA', b'WA')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[(b'Kids', b'Kids'), (b'Men', b'Men'), (b'Women', b'Women')], db_index=True, max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('state', models.CharField(choices=[(b'VIC', b'VIC'), (b'NSW', b'NSW'), (b'QLD', b'QLD'), (b'TAS', b'TAS'), (b'SA', b'SA'), (b'WA', b'WA')], max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.SalesPerson'),
        ),
    ]
