# Generated by Django 3.0.4 on 2020-05-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(choices=[('VIC', 'VIC'), ('NSW', 'NSW'), ('QLD', 'QLD'), ('TAS', 'TAS'), ('SA', 'SA'), ('WA', 'WA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Women', 'Women')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('VIC', 'VIC'), ('NSW', 'NSW'), ('QLD', 'QLD'), ('TAS', 'TAS'), ('SA', 'SA'), ('WA', 'WA')], max_length=3),
        ),
    ]
